services:
  todoapi:
    build: .
    ports:
      - 8000:8000
    volumes:
      - type: volume
        target: /code/media
      - ./.env:/code/.env:ro
      - type: bind
        source: db.sqlite3
        target: /code/db.sqlite3
