services:
  api:
    build: .
    container_name: todo-api
    ports:
      - mode: host
        target: 8000
        published: 8000
    volumes:
      - ./:/var/app
      - api-media:/var/app/media

volumes:
  api-media: