services:
  todoapi:
    build: .
    ports:
      - 8000:8000
    volumes:
      - type: volume
        target: /code/media
      # - type: bind
      #   source: .env
      #   target: /code/.env
      # - type: bind
      #   source: db.sqlite3
      #   target: /code/db.sqlite3

# configs:
#   db:
#     file: ./db.sqlite3
